# https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md
# set the Rust formatter to use the same 80-columns as we do
max_width = 80
wrap_comments = true
comment_width = 80

enum_discrim_align_threshold = 33
struct_field_align_threshold = 33

# Put single-expression functions on a single line:
#
#   fn lorem() -> usize { 42 }
#
fn_single_line = true
