# retronym (C) copyright Kroc Camen 2017, 2018
# BSD 2-clause licence; see LICENSE.TXT

[package]
name = "retronym"
version = "0.0.0"
authors = ["Kroc Camen <kroc@camendesign.com>"]

[dependencies]
pest = "2.0.2"
pest_derive = "2.0.1"

[profile.release]
panic = 'abort'